version: '3'

services:
    web:
        build: .
        ports:
            - "5000:5000"
        tty: true
        environment:
            - FLASK_APP=app
        command: flask run --host 0.0.0.0 -p 5000